using System;

namespace System.Data.SQLite
{
	internal enum SQLiteConfigOpsEnum
	{
		SQLITE_CONFIG_NONE = 0,
		SQLITE_CONFIG_SINGLETHREAD = 1,
		SQLITE_CONFIG_MULTITHREAD = 2,
		SQLITE_CONFIG_SERIALIZED = 3,
		SQLITE_CONFIG_MALLOC = 4,
		SQLITE_CONFIG_GETMALLOC = 5,
		SQLITE_CONFIG_SCRATCH = 6,
		SQLITE_CONFIG_PAGECACHE = 7,
		SQLITE_CONFIG_HEAP = 8,
		SQLITE_CONFIG_MEMSTATUS = 9,
		SQLITE_CONFIG_MUTEX = 10,
		SQLITE_CONFIG_GETMUTEX = 11,
		SQLITE_CONFIG_LOOKASIDE = 13,
		SQLITE_CONFIG_PCACHE = 14,
		SQLITE_CONFIG_GETPCACHE = 15,
		SQLITE_CONFIG_LOG = 16,
		SQLITE_CONFIG_URI = 17,
		SQLITE_CONFIG_PCACHE2 = 18,
		SQLITE_CONFIG_GETPCACHE2 = 19,
		SQLITE_CONFIG_COVERING_INDEX_SCAN = 20,
		SQLITE_CONFIG_SQLLOG = 21,
		SQLITE_CONFIG_MMAP_SIZE = 22,
		SQLITE_CONFIG_WIN32_HEAPSIZE = 23,
		SQLITE_CONFIG_PCACHE_HDRSZ = 24,
		SQLITE_CONFIG_PMASZ = 25
	}
}