using System;

namespace EntityWorker.SQLite
{
	public enum SQLiteConfigDbOpsEnum
	{
		SQLITE_DBCONFIG_NONE = 0,
		SQLITE_DBCONFIG_LOOKASIDE = 1001,
		SQLITE_DBCONFIG_ENABLE_FKEY = 1002,
		SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003,
		SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004,
		SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005
	}
}